debug: true
server:
  port: ${PORT:8080}
spring:
  sql:
    init:
      platform: postgresql
      mode: always

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://ep-soft-rice-a2e7q4y3.eu-central-1.aws.neon.tech/chiliDB?user=wikiDB_owner&password=u4cJ1lhyXtwY&sslmode=require
    username: ${DB_SALT:salt}
    password: ${DB_PASSWORD:secret}


  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR